services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres
          property: connectionString
    plan: free
    region: oregon

  - type: web
    name: frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: frontend/dist
    plan: free
    region: oregon

databases:
  - name: notes-db
    plan: free
    region: oregon